server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aop?autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

#    initialization-mode: always. A property under datasource.